with stg_job_ads as (select * from {{ source('hr_project_db', 'stg_ads') }})

select
    workplace_address__municipality,
    EMPLOYER__NAME,
    EMPLOYER__WORKPLACE,
    EMPLOYER__ORGANIZATION_NUMBER,
    WORKPLACE_ADDRESS__STREET_ADDRESS AS WORKPLACE_STREET_ADRESS,
    WORKPLACE_ADDRESS__REGION AS WORKPLACE_REGION,
    WORKPLACE_ADDRESS__POSTCODE AS WORKPLACE_POSTCODE,
    WORKPLACE_ADDRESS__CITY AS WORKPLACE_CITY,
    WORKPLACE_ADDRESS__COUNTRY AS WORKPLACE_COUNTRY
from stg_job_ads

