
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS hr_project_db;

CREATE WAREHOUSE hr_project_wh
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'HR group project.';

USE WAREHOUSE hr_project_wh;

CREATE SCHEMA IF NOT EXISTS warehouse;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;

DROP SCHEMA staging;
